name: AgrisenseAI
description: Assistant agricole Intelligent.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  http: ^1.1.0
  record:  ^6.0.0
  permission_handler: ^11.0.0
  flutter_tts: ^4.0.2
  path_provider: ^2.1.5
  audioplayers: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true